<?php 
  include '../models/header.html';
  include '../models/navbar.html'; ?>

<main id="main" class="main">

<div class="pagetitle">
  <h1>Create a Ticket</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="dashboard.php">Home</a></li>
      <li class="breadcrumb-item active">Tickets</li>
    </ol>
  </nav>
</div><!-- End Page Title -->

<section class="section ticket-create">
  <div class="row">
    <div class="col-mb-8">

      <div class="card pt-3">
        <div class="card-body pt-4">
            
        <form id="create-ticket" class="row g-3" novalidate>
                <div class="row mb-3 position-relative">
                    <label for="ticket_num" class="col-sm-2 col-form-label">Ticket Number <i class="bi bi-info-circle ms-1" data-bs-toggle="tooltip" data-bs-placement="top" title="This is auto-generated by the system."></i></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ticket_num" readonly>
                    </div>
                </div>
                
                <div class="row mb-3 position-relative">
                    <label for="concern_id" class="col-sm-2 col-form-label required">Concern</label>
                    <div class="col-sm-10">
                        <select id="concern_id" class="form-select" required>
                            <option selected disabled value="">Select the type of concern:</option>
                        </select>
                        <div class="invalid-feedback">Please select concern category.</div>
                    </div>
                </div>
        
                <div class="row mb-3 position-relative">    
                    <label for="concern_details" class="col-sm-2 col-form-label required">Concern Details</label>
                    <div class="col-sm-10">
                      <textarea class="form-control" id="concern_details" rows="4" placeholder="Enter concern details..." required></textarea>
                        <div class="invalid-feedback">Please enter concern details.</div>
                    </div>
                </div>

                <div class="row mb-3 position-relative">
                    <label for="date_filed" class="col-sm-2 col-form-label required">Date Filed</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control date_filed" id="date_filed" autocomplete="off" required>
                        <div class="invalid-feedback">Please choose date filed.</div>
                    </div>
                </div>

                <div class="row mb-3 position-relative">
                    <label for="account_id" class="col-sm-2 col-form-label required">Account ID</label>
                    <div class="col-sm-10">
                        <input list="accounts-list" type="text" class="form-control" id="account_id" required>
                        <div class="invalid-feedback">Please enter a valid account id.</div>

                        <datalist id="accounts-list"></datalist>
                    </div>
                </div>
        
                <div class ="text-center">
                    <button type="submit" class="btn btn-primary">Submit Ticket</button>
                </div>

            </form>


        </div>
      </div>

    </div>
  </div>
</section>

</main><!-- End #main -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="../assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../assets/vendor/chart.js/chart.min.js"></script>
  <script src="../assets/vendor/echarts/echarts.min.js"></script>
  <script src="../assets/vendor/quill/quill.min.js"></script>
  <script src="../assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="../assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="../assets/vendor/php-email-form/validate.js"></script>

  <!-- Datepicker -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

  <!-- Template Main JS File -->
  <script src="../assets/js/main.js"></script>

  <!-- Backend JS File -->
  <script src="../js/main.js"></script>
  <script src="../js/tickets.js"></script>

</body>
</html>